export const FOCUS_START_DATE = "FOCUS_START_DATE";
export const FOCUS_END_DATE = "FOCUS_END_DATE";
export const SEARCH_CAMPAIGN_RECORDS = "SEARCH_CAMPAIGN_RECORDS";
export const ADD_CAMPAIGNS = "ADD_CAMPAIGNS";
export const SET_USERS = "SET_USERS";
export const GET_USERS = "GET_USERS";
export const SET_START_DATE = "SET_START_DATE";
export const SET_END_DATE = "SET_END_DATE";
